os: linux
dist: trusty
language: generic
#
install:
  - pushd .travis
  - mkdir work
  - cd work
  - wget http://wotho.ethz.ch/tk4-/tk4-_v1.00_current.zip
  - unzip tk4-_v1.00_current.zip
  - rm tk4-_v1.00_current.zip
  - popd
#
script:
  - pushd .travis/work
  - ./mvs &
  - pidherc=$!
  - (sleep 1200; kill -9 $pidherc) &
  - pidtout=$!
  - sleep 180
  - popd
#
  - export PATH=$PATH:$PWD/bin:$PWD/herc-tools/bin
  - (cd codes   &&  hercjis -c C -r 20 s370_perf_t.JES)
  - (cd .travis &&  hercjis -c C       shutdown.jcl)
  - wait $pidherc
  - kill $pidtout || true
#
  - pushd .travis/work/prt
  - hercjos -db -dt -i prt00e.txt
  - hercjsu -asum *PERF* || (echo "FAILED steps:" && hercjsu -fail *PERF*)
  - s370_perf_ana *PERF* > travis_perf.dat
  - s370_perf_sort -k ins travis_perf.dat
  - s370_perf_mark travis_perf.dat
  - popd
#
  - .travis/deploy.sh
